export const siteConfig = {
  name: "PDFForge",
  nameShort: "PDFForge",
  legalName: "PDFForge Inc.",
  description:
    "Fast, secure, browser-based PDF tools: convert, merge, split, compress, edit and OCR documents — free with no watermarks. No login required. All tools work directly in your browser.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://pdfforge.example.com",
  ogImage: "/og.svg",
  twitterHandle: "@pdfforge",
  googleSiteVerification: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION ?? "",
  keywords: [
    "pdf tools",
    "merge pdf",
    "split pdf",
    "compress pdf",
    "pdf to word",
    "word to pdf",
    "pdf converter",
    "ocr pdf",
    "free pdf tools",
    "online pdf editor",
    "pdf compressor online",
    "merge pdf files free",
    "split pdf online",
    "pdf to jpg converter",
    "pdf to text extractor",
    "ai pdf tools",
    "pdf tool no signup",
    "pdf tool no login",
    "browser pdf tool",
    "secure pdf converter",
  ],
  nav: {
    tools: { label: "Tools", href: "/tools" },
    pricing: { label: "Pricing", href: "/pricing" },
    docs: { label: "Docs", href: "/docs" },
    dashboard: { label: "Dashboard", href: "/dashboard" },
    admin: { label: "Admin", href: "/admin" },
  },
} as const;

export type SiteConfig = typeof siteConfig;
